/**
 * English language pack
 */
export const en = {
  // Page title
  title: 'Invoice Generator',
  
  // Language switch
  language: 'Language',
  chinese: '中文',
  english: 'English',
  
  // Company information
  companyInfo: 'Company Information',
  companyName: 'Company Name',
  abn: 'ABN',
  address: 'Address',
  phone: 'Phone',
  email: 'Email',
  slogan: 'Slogan (Optional)',
  
  // Client information
  clientInfo: 'Client Information',
  clientName: 'Client Name',
  clientAddress: 'Client Address',
  clientPhone: 'Client Phone',
  
  // Invoice information
  invoiceInfo: 'Invoice Information',
  invoiceNumber: 'Invoice Number',
  date: 'Date',
  projectDescription: 'Project Description (Optional)',
  poNumber: 'PO Number (Optional)',
  
  // Items
  items: 'Items',
  itemName: 'Item/Service Name',
  quantity: 'Quantity',
  unitPrice: 'Unit Price',
  subtotal: 'Subtotal',
  
  // GST settings
  gstSettings: 'GST Settings',
  includeGST: 'Include GST',
  gstRate: 'GST Rate',
  
  // Calculations
  gst: 'GST',
  total: 'Total',
  
  // Buttons
  generatePDF: 'Generate PDF',
  resetForm: 'Reset Form',
  preview: 'Preview',
  
  // Invoice preview
  invoice: 'INVOICE',
  invoiceTo: 'Invoice To',
  invoiceDate: 'Invoice Date',
  dueDate: 'Due Date',
  paymentTerms: 'Payment Terms',
  
  // Footer
  thankYou: 'Thank you for your business!',
  paymentInfo: 'Payment Information',
  bankAccount: 'Bank Account',
  bsb: 'BSB',
  accountNumber: 'Account Number',
  
  // Tips
  required: 'Required',
  optional: 'Optional',
  autoGenerated: 'Auto Generated',
  
  // Responsive tips
  smallScreen: 'Small Screen Mode',
  previewHidden: 'Preview Hidden',
  showPreview: 'Show Preview',
  hidePreview: 'Hide Preview'
}; 