/**
 * 中文语言包
 */
export const zh = {
  // 页面标题
  title: '发票生成器',
  
  // 语言切换
  language: '语言',
  chinese: '中文',
  english: 'English',
  
  // 公司信息
  companyInfo: '公司信息',
  companyName: '公司名称',
  abn: 'ABN',
  address: '地址',
  phone: '电话',
  email: '邮箱',
  slogan: '口号（可选）',
  
  // 客户信息
  clientInfo: '客户信息',
  clientName: '客户名称',
  clientAddress: '客户地址',
  clientPhone: '客户电话',
  
  // 发票信息
  invoiceInfo: '发票信息',
  invoiceNumber: '发票编号',
  date: '日期',
  projectDescription: '项目描述（可选）',
  poNumber: 'PO号（可选）',
  
  // 明细
  items: '明细',
  itemName: '商品/服务名称',
  quantity: '数量',
  unitPrice: '单价',
  subtotal: '小计',
  
  // GST设置
  gstSettings: 'GST设置',
  includeGST: '包含GST',
  gstRate: 'GST税率',
  
  // 计算
  gst: 'GST',
  total: '总计',
  
  // 按钮
  generatePDF: '生成PDF',
  resetForm: '重置表单',
  preview: '预览',
  
  // 发票预览
  invoice: '发票',
  invoiceTo: '发票至',
  invoiceDate: '发票日期',
  dueDate: '到期日期',
  paymentTerms: '付款条件',
  
  // 页脚
  thankYou: '感谢您的惠顾！',
  paymentInfo: '付款信息',
  bankAccount: '银行账户',
  bsb: 'BSB',
  accountNumber: '账号',
  
  // 提示信息
  required: '必填',
  optional: '可选',
  autoGenerated: '自动生成',
  
  // 响应式提示
  smallScreen: '小屏幕模式',
  previewHidden: '预览已隐藏',
  showPreview: '显示预览',
  hidePreview: '隐藏预览'
}; 